#!/usr/bin/env python
''' treeconf.util

Cross module utilities
'''

def normalize(var, type=None, **kwargs):
    if var is None:
        return None
    if type is None:
        return var
    if type is basestring:
        return str(type)
    elif type is int:
        return int(type)
    elif type is hex:
        return int(type, 16)
    elif type is bin:
        return int(type, 2)
    elif type is oct:
        return int(type, 8)
    else:
        raise ValueError('Unrecognized type argument. '
            'Cannot normalize variable.')
